version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: Microsoft.DotNet.XliffTasks
    versions:
    - "> 1.0.0-beta.19562.1"
- package-ecosystem: npm
  directory: "/src/LondonTravel.Site"
  schedule:
    interval: daily
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/jasmine"
    versions:
    - "> 3.4.0"
